---

- name: copy gemrc
  template: >
    src=gemrc
    dest=~/.gemrc
  tags:
    - rails

- name: install rails
  gem: >
    name=rails
    state=latest
    executable=~/.rbenv/shims/gem
  tags:
    - rails
