---

- name: run the equivalent of "apt-get update"
  apt: update_cache=yes
  sudo: yes
  tags: common

- name: update all packages to the latest version
  apt: upgrade=dist
  sudo: yes
  tags: common

- name: install dependencies for rails enviroment
  apt: pkg={{item}} state=latest update_cache=yes
  sudo: yes
  with_items:
    - build-essential
    - curl
    - git-core
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libsqlite3-dev
    - libxml2-dev
    - libxslt1-dev
    - nodejs
    - sqlite3
    - tmux
    - vim
    - zlib1g-dev
  tags: common

