- hosts: vagrant
  user: vagrant
  tasks:
    - name: run the equivalent of "apt-get update"
      apt: update_cache=yes
      sudo: yes

    - name: update all packages to the latest version
      apt: upgrade=dist
      sudo: yes

    - name: install common dependencies for rails gems
      apt: pkg={{item}} state=latest update_cache=yes
      sudo: yes
      with_items:
        - build-essential
        - curl
        - git
        - libmysqld-dev
        - libreadline-dev
        - libssl-dev
        - libxml2-dev
        - libxslt1-dev
        - libyaml-dev
        - nodejs
        - tmux
        - vim

    - name: install mysql
      apt: pkg={{item}} state=present
      sudo: yes
      with_items:
        - mysql-server
        - mysql-client

    - name: install rvm
      shell: curl -L https://get.rvm.io | bash

    - name: source the rvm files
      shell: /bin/bash -c 'source /home/vagrant/.rvm/scripts/rvm'

    - name: install ruby 2.1.1
      shell: /home/vagrant/.rvm/bin/rvm install --default 2.1.1

    - name: install bundler
      gem: name=bundler

    - name: install rails
      gem: name=rails state=latest
