---

- name: install rbenv
  sudo: yes
  git: repo=git://github.com/sstephenson/rbenv.git dest=~/.rbenv
  tags: rbenv

- name: Add ~.rbenv/bin to PATH
  sudo: yes
  lineinfile: >
    dest="~/.profile"
    line="export PATH=$HOME/.rbenv/bin:$PATH"
  tags: rbenv

- name: Eval rbenv init in ~/.profile
  sudo: yes
  sudo_user: "{{ rbenv.user }}"
  lineinfile: >
    dest="~/.profile"
    line='eval "$(rbenv init -)"'
  tags: rbenv

- name: Install ruby-build as rbenv plugin
  sudo: yes
  git: repo=https://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build
  tags: rbenv

- name: install ruby 2.1.1
  command: "rbenv install 2.1.1"
  tags: rbenv

- name: set default ruby version to 2.1.1
  command "rbenv global 2.1.1"
  tags: rbenv
