---

- name: install rbenv
  git: repo=git://github.com/sstephenson/rbenv.git dest=~/.rbenv
  tags: rbenv

- name: add ~.rbenv/bin to PATH
  lineinfile: >
    dest="~/.bashrc"
    line="export PATH=$HOME/.rbenv/bin:$PATH"
  tags: rbenv

- name: eval rbenv init in ~/.bashrc
  lineinfile: >
    dest="~/.bashrc"
    line='eval "$(rbenv init -)"'
  tags: rbenv

- name: install ruby-build as rbenv plugin
  git: repo=https://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build
  tags: rbenv

- name: install ruby 2.1.1
  shell: "curl -fsSL https://gist.github.com/mislav/a18b9d7f0dc5b9efc162.txt | rbenv install --patch 2.1.1"
  tags: rbenv

- name: set default ruby version to 2.1.1
  command: "rbenv global 2.1.1"
  tags: rbenv
